# Workflow used to test a Power Platform service connection with the name provided as variable

# Variables to define when creating the pipeline in Azure DevOps
# ServiceConnectionName - String - Not secret - Let user override

trigger: none # Pipeline triggered manually
pr: none # Pipeline not triggered on a pull request

pool:
  vmImage: 'windows-2019'

steps:
# Install the Power Platform Build Tools extension on the agent
- task: PowerPlatformToolInstaller@0
  displayName: 'Power Platform Tool Installer '

# Execute the "Who Am I" action to check that the service connection provided is operational
- task: PowerPlatformWhoAmi@0
  displayName: 'Power Platform WhoAmI '
  inputs:
    authenticationType: PowerPlatformSPN
    PowerPlatformSPN: '$(ServiceConnectionName)'